### DISCUSSION TITLE
Which items control these background colors?

### DISCUSSION THREAD

**Discussion by spamegg1** [catppuccin/gtk#91] [Q&A]
I'm using Catppuccin Mocha Mauve GTK 3.0 theme on the Cinnamon desktop.

I am looking for the lines of code in `gtk.css` that control these background colors (I think they have something to do with `view` or `selected` or `hover`). They are a bit too indistinct / difficult to see / distinguish for me, I'd like to change them to some shades of pink / purple.

This is the sidebar in a Nemo window (Nemo is the file manager for Cinnamon desktop environment). One line is selected, one is unselected, one has the mouse hovering over it:
![Screenshot from 2023-04-28 19-13-50](https://user-images.githubusercontent.com/4255997/235199963-03c53d0f-53cb-48e4-9b75-0ce999366b9e.png)

This is the sidebar in Geany. One line is selected, one is unselected, one has the mouse hovering over it:
![Screenshot from 2023-04-28 19-11-10](https://user-images.githubusercontent.com/4255997/235199631-cee25c0b-8068-4f43-b17a-8612c8275912.png)

This is from Deluge (a Bittorrent client), here on the right, one line is selected, one is unselected, and one has the mouse hovering over it:
![Screenshot from 2023-04-28 19-16-34](https://user-images.githubusercontent.com/4255997/235200502-12797d8e-784a-4278-a827-10854f40390b.png)

I believe one of them is:
```css
.view:hover {
  box-shadow: inset 0 0 0 9999px alpha(currentColor, 0.08);
}
```
and another one (for mouse hovering over it) is:
```css
menu menuitem:hover,
.menu menuitem:hover,
.context-menu menuitem:hover {
  background-color: alpha(currentColor, 0.08);
}
```
Are these right?
Which one controls the selected line?
