### ISSUE TITLE
KiCad does not display correctly.

### ISSUE THREAD

**Issue by wirano** [catppuccin/gtk#75]
- OS: Arch Linux
- Kernel: 6.1.9-zen1-1-zen
- DE: Plasma 5.26.5
- WM: kwin
- WM Theme: Lightly
- Plasma Theme: Catppuccin Latte
- GTK Theme: Catppuccin-Latte-Standard-Teal-Light
- KiCad version: 7.0.0.rc2.r202.ge8397a33bb-1 (it also could reproduce on 6.0.11-1)

How to reproduce:  
1. Set GTK Theme to Catppuccin
2. Open KiCad
3. You will see:

![Catppuccin-Latte-Standard-Teal-Light](https://user-images.githubusercontent.com/13417232/216775034-580b14f4-6372-4c01-84a8-1d91fc8b6688.png)

5. Change GNOME/GTK Style to Adwaita/Breeze
6. Open KiCad
7. It looks with no problem:

![Breeze](https://user-images.githubusercontent.com/13417232/216775185-a8169c0f-1654-4803-9dea-2f8f8c89d7a0.png)

**Comment by covertneko** [comment]
Same here on NixOS using Catppuccin-Mocha-Standard-Mauve-Dark:
![image](https://user-images.githubusercontent.com/2039829/219903256-8e178fb1-8745-472b-bb19-479073dd8b57.png)

**Comment by MathisP75** [comment]
Same for me. This is a problem from the Colloid theme it is based on, since it does the same when using Colloid.

**Comment by covertneko** [comment]
For anyone who comes across this and wants a quick fix, I've narrowed it down to the following rule at gtk-dark.css:645:
```css
actionbar > revealer > box .linked > button:not(.suggested-action):not(.destructive-action), button {
  transition: all 75ms cubic-bezier(0, 0, 0.2, 1), background-size 300ms cubic-bezier(0, 0, 0.2, 1), background-image 1200ms cubic-bezier(0, 0, 0.2, 1);
  outline: none;
  box-shadow: inset 0 0 0 9999px transparent;
  background-color: rgba(255, 255, 255, 0.08);
  background-image: radial-gradient(circle, transparent 10%, transparent 0%);
  background-repeat: no-repeat;
  background-position: center;
  background-size: 1000% 1000%;
  color: #FFFFFF;
}
```

Specifically `background-color` on the `button` selector. I've just commented that property out locally because I'm impatient.

As far as I can tell, this comes from [here](https://github.com/vinceliuice/Colloid-gtk-theme/blob/6b519534f852d55daa95e57bcae21e34a120909e/src/sass/gtk/_drawing-3.0.scss#L99), with the color being set [here](https://github.com/vinceliuice/Colloid-gtk-theme/blob/236587d1e2de59d7b269a227fd8bf22e0463bfeb/src/sass/_colors.scss#L127). I'm not entirely sure why this is like this or how to fix it properly, but I'll create an issue upstream.
